server:
  servlet:
    context-path: /api

spring:
  # 채팅 테스트용
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false
#    template-loader-path: classpath:/templates
#    prefix: /chat/
#    suffix: .ftl

  cache:
    type: redis
  redis:
    # 로컬 환경
    host: localhost
    # 도커 환경
#    host: 172.17.0.3

    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    prefix: /chat/
    suffix: .ftl

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  # swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 환경
#    url: jdbc:mysql://localhost:3306/testest?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
#    username: root
#    password: ssafy
    # 배포 도커 환경
#    url: jdbc:mysql://ubuntu_db-mysql_1/beedly?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
#    username: ssafy
#    password: yfass1234
    # 로컬에서 ec2 DB로 연결
    url: jdbc:mysql://i7a601.p.ssafy.io:3306/beedly?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: ssafy
    password: yfass1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
        show_sql: true

    open-in-view: false

  data:
    web:
      pageable:
        default-per-size: 20
        max-page-size: 2000 

token:
  # 일단 하루
  expiration_time: 86400000
  secret: secretcode

cloud:
  aws:
    credentials:
      accessKey: AKIASQN6UNY67SNTSHSU
      secretKey: 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
    s3:
      bucket: beedly-img
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug

kakao:
  restapikey: 3862f54bf3ad04ea7d23f310de16a274