spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  # swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 환경
#    url: jdbc:mysql://localhost:3306/testest?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
#    username: root
#    password: ssafy
    # 배포 도커 환경
#    url: jdbc:mysql://ubuntu_db-mysql_1/beedly?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
#    username: ssafy
#    password: yfass1234
    # 로컬에서 ec2 DB로 연결
    url: jdbc:mysql://i7a601.p.ssafy.io:3306/beedly?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: yfass1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
    open-in-view: false

  data:
    web:
      pageable:
        default-per-size: 10
        max-page-size: 2000 

token:
  # 일단 하루
  expiration_time: 86400000
  secret: secretcode

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug

kakao:
  restapikey: 3862f54bf3ad04ea7d23f310de16a274